language: ruby
rvm:
- 2.0.0
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
deploy:
  provider: heroku
  api_key:
    secure: lLGHftzP5wPgcOFA9YPyrMF6Rgk3Xs1UEk8r9OyfXe2DGeJw9aBW4grL9bHPt3eGpsshacwHXkbr7QgdmsjY02MLYzsmcvRRC1NWIJTujSeXhnAT7zSmTJ8XR63lWhzdpE/ak/+GIj1pHYYFzowVrNGbKsQTUYJjP68yLNkldLM=
  app: still-brushlands-2241
  run: "rake db:migrate"
  on:
    repo: Kaermes/ratebeer
